# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: install-required-packages.yml
- include_tasks: add-storm-user.yml
- include_tasks: install-apache-storm.yml
- include_tasks: install-apache-zookeeper.yml
  when: (zk_nodes | default([])) == []
- include_role:
    name: configure-storm-nodes
- include_tasks: create-zookeeper-services.yml
  when: (zk_nodes | default([])) == []
- include_tasks: create-storm-services.yml
- include_tasks: enable-zookeeper-services.yml
  when: (zk_nodes | default([])) == []
- include_tasks: enable-storm-services.yml
- include_tasks: start-zookeeper-services.yml
  when: (zk_nodes | default([])) == []
- include_tasks: start-storm-services.yml
