# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include: install-required-packages.yml static=no
- include: add-storm-user.yml static=no
- include: install-apache-storm.yml static=no
- include: install-apache-zookeeper.yml static=no
  when: (zk_nodes | default([])) == []
- include_role:
    name: configure-storm-nodes
- include: create-zookeeper-services.yml static=no
  when: (zk_nodes | default([])) == []
- include: create-storm-services.yml static=no
- include: enable-zookeeper-services.yml static=no
  when: (zk_nodes | default([])) == []
- include: enable-storm-services.yml static=no
- include: start-zookeeper-services.yml static=no
  when: (zk_nodes | default([])) == []
- include: start-storm-services.yml static=no